### ISSUE TITLE
One suggestion

### ISSUE THREAD

**Issue by mitchelsevere** [TSSaint/SNKRv1#1]
Easier to give multiple classes to these elements since they use the same styling (DRY principles).

Could use css

```css
.logo {
    background-color: red; 
    font-size: 100px; 
    font-weight: 800; 
    font-style: oblique; 
    letter-spacing: 0px; 
    padding-top: 30px
}

.a-links {
   font-size: 30px; 
   font-weight: 700
}
```
instead of in-line styling

```html
<a style="background-color: red; font-size: 100px; font-weight: 800; font-style: oblique; letter-spacing: 0px; padding-top: 30px;"class="links big" href="#">SNKR</a>
<div id="ind-container">
    <ul>
      <li><a style="font-size: 30px; font-weight: 700;" class="links big" href="/shoes/">HOME</a></li>
      <li><a style="font-size: 30px; font-weight: 700;" class="links big" href="/auth/login">SIGN IN</a></li>
      <li><a style="font-size: 30px; font-weight: 700;" class="links big" href="/auth/register">REGISTER</a></li>
    </ul>
</div>
```
